// Elevate frontend — PDF feedback generator
// Uses jsPDF + autotable (loaded via CDN in index.html)

export function generateFeedbackPdf(data) {
  const { scenario, feedback, score, date, userName } = data;
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  // Header
  doc.setFillColor(109, 94, 252); // #6d5efc
  doc.rect(0, 0, 595.28, 70, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Elevate — Feedback Report", 40, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Workforce-readiness companion", 40, 58);

  // Meta
  doc.setFontSize(11);
  doc.text(`Date: ${date || "—"}`, 40, 90);
  doc.text(`User: ${userName || "—"}`, 300, 90);
  doc.text(`Scenario: ${scenario?.title || "—"}`, 40, 106);
  doc.text(`Category: ${scenario?.category || "—"}`, 300, 106);

  // Score
  doc.setDrawColor(109, 94, 252);
  doc.setLineWidth(1);
  doc.line(40, 118, 555, 118);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(`Score: ${score ?? 0} / 100`, 40, 136);

  // Feedback sections
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("What went well", 40, 162);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const wellLines = doc.splitTextToSize(feedback?.whatWentWell || "", 500);
  doc.text(wellLines, 40, 178);

  const improveY = 178 + wellLines.length * 16 + 14;
  doc.setFont("helvetica", "bold");
  doc.text("What to improve", 40, improveY);
  doc.setFont("helvetica", "normal");
  const improveLines = doc.splitTextToSize(feedback?.whatToImprove || "", 500);
  doc.text(improveLines, 40, improveY + 16);

  const nextY = improveY + 16 + improveLines.length * 16 + 14;
  doc.setFont("helvetica", "bold");
  doc.text("Next steps", 40, nextY);
  doc.setFont("helvetica", "normal");
  const nextLines = doc.splitTextToSize(feedback?.nextSteps || "", 500);
  doc.text(nextLines, 40, nextY + 16);

  let retryY = nextY + 16 + nextLines.length * 16 + 14;
  if (feedback?.retryAdvice) {
    doc.setFont("helvetica", "bold");
    doc.text("Try again", 40, retryY);
    doc.setFont("helvetica", "normal");
    const retryLines = doc.splitTextToSize(feedback.retryAdvice, 500);
    doc.text(retryLines, 40, retryY + 16);
    retryY = retryY + 16 + retryLines.length * 16 + 14;
  }

  // Skills table
  const skills = (scenario?.skills || []).map((s) => ({
    name: s.skill?.name || s.name || "Skill",
    weight: s.weight ?? 1,
  }));
  if (skills.length) {
    retryY += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Skills practised", 40, retryY);
    retryY += 8;
    doc.autoTable({
      startY: retryY,
      head: [["Skill", "Weight"]],
      body: skills.map((s) => [s.name, String(s.weight)]),
      styles: { fontSize: 11 },
      headStyles: { fillColor: [109, 94, 252], textColor: [255, 255, 255] },
      margin: { left: 40, right: 40 },
    });
  }

  // Footer
  const pageHeight = doc.internal.pageHeight;
  doc.setFontSize(9);
  doc.text("Generated by Elevate — keep this report to track your progress.", 40, pageHeight - 20);

  return doc;
}

export function downloadFeedbackPdf(data, filename = "elevate-feedback.pdf") {
  const doc = generateFeedbackPdf(data);
  doc.save(filename);
}

export function openFeedbackPdf(data, filename = "elevate-feedback.pdf") {
  const doc = generateFeedbackPdf(data);
  const url = doc.output("bloburl");
  window.open(url, "_blank", "noopener,noreferrer");
}